// <auto-generated />
namespace Mvc4WebRole.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    public sealed partial class Image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Image));

        string IMigrationMetadata.Id
        {
            get { return "201312051604383_Image"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
